### ISSUE TITLE
Can I know where the ID list is?

### ISSUE THREAD

**Issue by freeze-dolphin** [TheBusyBiscuit/Slimefun4-Wiki#37]
## Description
In the past, slimefun wiki included a page which listed all ids in slimefun, but now I cannot find it anymore.
I think the id list is really necessary for a slimefun addon developer. So can you add it back?

## Slimefun Version
Slimefun v4.1.15

**Comment by WalshyDev** [comment]
You don't need all the IDs, just use the SlimefunItems class to access whatever (or get its ID). That way at least it wouldn't break if we ever change the ID.

**Comment by freeze-dolphin** [comment]
> You don't need all the IDs, just use the SlimefunItems class to access whatever (or get its ID). That way at least it wouldn't break if we ever change the ID.

Thank you very much :D
